import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Poppins } from 'next/font/google';
import Carousel from "@/components/Carousel";
import SlickTabs from "@/components/SlickTabs";
import BetList from "@/components/Betlist";
import News from "@/components/News";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const integralCF = localFont({
  src: './fonts/Integral-CF/Demo_Fonts/Fontspring-DEMO-integralcf-regular.otf',
  weight: '400, 700',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Navbar />
        <div className="bg-black px-[30px]">
          <Carousel />
          <SlickTabs />
          <BetList />
          <News />
        </div>
        <Footer />
        {/* {children} */}
      </body>
    </html>
  );
}
